name: zentask
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  chewie: ^1.7.5
  google_sign_in: ^6.1.6

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4

  rxdart: ^0.27.7

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Register the directory containing your Google logo
  assets:
    - assets/images/

